POST http://localhost:3002/api/cocktails/
Content-Type: application/json

{
  "name": "asdf",
  "ingredients": "[ 'ron', 'coca', 'lime' ]",
  "image": "https://images.cocktailflow.com/v1/cocktail/w_300,h_540/cocktail_gin_tonic-1.png",
  "id": "9",
  "amountOfIngredients": 3
}